const ads = [
    {
        title: "Vélo tout terrain en bon état",
        description:
            "Vélo VTT, peu utilisé, en très bon état, idéal pour randonnées.",
        city: "Toulon",
        price: 120,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Demande de service de plomberie",
        description:
            "Recherche un plombier pour une intervention rapide sur une fuite d'eau.",
        city: "Lyon",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Appartement T2 à louer",
        description:
            "Appartement 2 pièces, 50m², proche du centre-ville et des commerces.",
        city: "Marseille",
        price: 650,
        typeEnum: "OFFER",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche jeux vidéo d'occasion",
        description:
            "Je suis à la recherche de jeux vidéo d'occasion pour PS4 et Nintendo Switch.",
        city: "Toulouse",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Offre de baby-sitting",
        description:
            "Disponible pour garder vos enfants en soirée ou le week-end. Expérience vérifiable.",
        city: "Nantes",
        price: 10,
        typeEnum: "OFFER",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de maison de vacances",
        description:
            "Maison de vacances spacieuse, 3 chambres, à 5 minutes de la plage. Idéal pour famille.",
        city: "Nice",
        price: 1200,
        typeEnum: "OFFER",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'un ordinateur portable",
        description:
            "Ordinateur portable en très bon état, parfait pour le travail ou le jeu.",
        city: "Bordeaux",
        price: 500,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Demande de service de jardinage",
        description:
            "Recherche un jardinier pour entretenir mon jardin une fois par semaine.",
        city: "Lille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Voiture d'occasion à vendre",
        description:
            "Peugeot 208 d'occasion, année 2018, faible kilométrage, en bon état.",
        city: "Rennes",
        price: 7500,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche une assistante administrative",
        description:
            "Entreprise recherche une assistante administrative pour un poste à mi-temps.",
        city: "Strasbourg",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "EMPLOYMENT",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de guitare pour débutants",
        description:
            "Donne cours de guitare pour débutants. Possibilité à domicile ou en ligne.",
        city: "Paris",
        price: 25,
        typeEnum: "OFFER",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Achat de meubles anciens",
        description:
            "Cherche à acheter des meubles anciens en bois pour rénovation.",
        city: "Lille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chiot labrador à vendre",
        description:
            "Chiot labrador de 3 mois, vacciné et en bonne santé, cherche famille aimante.",
        city: "Lyon",
        price: 600,
        typeEnum: "OFFER",
        categoryEnum: "ANIMALS",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Demande d'emploi en marketing digital",
        description:
            "Cherche un poste en marketing digital, expérience de 2 ans dans le secteur.",
        city: "Bordeaux",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "EMPLOYMENT",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de livres d'occasion",
        description:
            "Lot de livres d'occasion en très bon état, genres variés (romans, essais).",
        city: "Toulouse",
        price: 30,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Demande de réparation d'ordinateur",
        description:
            "Cherche technicien pour réparer un ordinateur portable Lenovo. Écran cassé.",
        city: "Marseille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location d'un camion de déménagement",
        description:
            "Camion de déménagement disponible à la location, permis B suffisant.",
        city: "Nice",
        price: 80,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche stage en développement web",
        description:
            "Étudiant en développement web, recherche un stage de 3 mois.",
        city: "Nantes",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "EMPLOYMENT",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de matériel de camping",
        description:
            "Matériel de camping complet à louer : tente, sacs de couchage, réchaud.",
        city: "Montpellier",
        price: 50,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Don de vêtements pour bébé",
        description: "Donne vêtements pour bébé, taille 0-6 mois. En bon état.",
        city: "Rennes",
        price: 0,
        typeEnum: "OFFER",
        categoryEnum: "FASHION",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Table de jardin en bois",
        description:
            "Table en teck, pour 6 personnes, très bon état, idéale pour l'été.",
        city: "Nice",
        price: 150,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Console de jeux Nintendo Switch",
        description:
            "En excellent état, avec 3 jeux inclus. Idéal pour les soirées entre amis.",
        city: "Marseille",
        price: 250,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chambre à louer à Marseille",
        description:
            "Chambre meublée à partager dans un appartement proche du centre.",
        city: "Marseille",
        price: 400,
        typeEnum: "DEMAND",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chiots Labrador à donner",
        description:
            "Je donne des chiots Labrador, très affectueux et joueurs.",
        city: "Lyon",
        price: 0,
        typeEnum: "OFFER",
        categoryEnum: "ANIMALS",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche un freelance développeur web",
        description:
            "Nous cherchons un développeur web freelance pour un projet de site vitrine.",
        city: "Paris",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "EMPLOYMENT",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de vélos d'occasion",
        description:
            "Plusieurs modèles disponibles, en très bon état, à des prix attractifs.",
        city: "Toulouse",
        price: 80,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Jeux de société à vendre",
        description:
            "Une collection de jeux de société en excellent état. Idéal pour les soirées en famille.",
        city: "Strasbourg",
        price: 30,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cuisinier à domicile",
        description:
            "Recherche un cuisinier à domicile pour préparer des repas pour événements.",
        city: "Bordeaux",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Lits superposés à vendre",
        description: "Lits superposés en bon état, avec matelas inclus.",
        city: "Nantes",
        price: 150,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'objets de mode vintage",
        description:
            "Robe vintage, sac à main et accessoires en excellent état.",
        city: "Lille",
        price: 60,
        typeEnum: "OFFER",
        categoryEnum: "FASHION",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Canapé en cuir",
        description: "Grand canapé en cuir noir, très confortable, comme neuf.",
        city: "Marseille",
        price: 600,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "iPhone 11 à vendre",
        description: "iPhone 11 en parfait état, 64 Go, avec accessoires.",
        city: "Lyon",
        price: 400,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de guitare à domicile",
        description:
            "Professeur de guitare propose des cours à domicile pour tous niveaux.",
        city: "Nice",
        price: 30,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Coffret de maquillage",
        description:
            "Coffret de maquillage avec palettes et pinceaux, jamais utilisé.",
        city: "Toulouse",
        price: 50,
        typeEnum: "OFFER",
        categoryEnum: "FASHION",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Jeux vidéo PS5 à vendre",
        description:
            "Jeux vidéo PS5 en excellent état, quelques titres disponibles.",
        city: "Bordeaux",
        price: 40,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Tapis d'extérieur",
        description:
            "Tapis d'extérieur résistant aux intempéries, parfait pour le jardin.",
        city: "Nice",
        price: 80,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche colocation à Lyon",
        description:
            "Je cherche une colocation dans un appartement spacieux à Lyon.",
        city: "Lyon",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Ensemble de golf complet",
        description:
            "Vends ensemble de golf complet, clubs, sac et accessoires.",
        city: "Strasbourg",
        price: 200,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Bureau en bois massif",
        description:
            "Bureau en bois massif, en très bon état, idéal pour le télétravail.",
        city: "Nantes",
        price: 300,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Service de nettoyage",
        description: "Propose service de nettoyage pour maisons et bureaux.",
        city: "Marseille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Trottinette électrique",
        description:
            "Trottinette électrique en bon état, idéale pour les trajets en ville.",
        city: "Paris",
        price: 250,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Livres de développement personnel",
        description: "Vends livres de développement personnel, certains neufs.",
        city: "Toulouse",
        price: 15,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche babysitter",
        description:
            "Recherche une babysitter pour s'occuper de mes enfants le soir.",
        city: "Nantes",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de skis",
        description:
            "Skis en excellent état avec chaussures, idéaux pour les vacances.",
        city: "Chamonix",
        price: 150,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Canapés d'angle",
        description:
            "Canapé d'angle convertible, parfait pour les petits espaces.",
        city: "Bordeaux",
        price: 500,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Appartement à vendre",
        description:
            "Appartement T3 à vendre, centre-ville, proche des commerces.",
        city: "Lille",
        price: 250000,
        typeEnum: "OFFER",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Annonces publicitaires",
        description:
            "Recherche un freelance pour des annonces publicitaires sur les réseaux sociaux.",
        city: "Paris",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "EMPLOYMENT",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Guitare acoustique à vendre",
        description: "Guitare acoustique, presque neuve, avec housse.",
        city: "Strasbourg",
        price: 100,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche des meubles à donner",
        description:
            "Je recherche des meubles en bon état à donner ou vendre à bas prix.",
        city: "Nice",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Bureau en bois",
        description: "Bureau en bois massif, parfait pour le télétravail.",
        city: "Nantes",
        price: 250,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Jeux de société à vendre",
        description: "Collection de jeux de société, à vendre en lot.",
        city: "Lille",
        price: 100,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de guitare",
        description: "Propose des cours de guitare pour débutants.",
        city: "Marseille",
        price: 20,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de studio",
        description: "Studio à louer en centre-ville, idéal pour étudiant.",
        city: "Lyon",
        price: 500,
        typeEnum: "OFFER",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends canapé convertible",
        description:
            "Canapé convertible en bon état, parfait pour les petits espaces.",
        city: "Paris",
        price: 300,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Bricolage à domicile",
        description: "Je propose mes services pour des travaux de bricolage.",
        city: "Nice",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'outils de jardinage",
        description: "Outils de jardinage à vendre, presque neufs.",
        city: "Toulouse",
        price: 50,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chaise de bureau ergonomique",
        description: "Chaise de bureau ergonomique, très confortable.",
        city: "Bordeaux",
        price: 120,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Foulard en soie",
        description: "Foulard en soie, jamais porté.",
        city: "Marseille",
        price: 30,
        typeEnum: "OFFER",
        categoryEnum: "FASHION",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche assistante",
        description:
            "Je cherche une assistante pour gérer mon emploi du temps.",
        city: "Strasbourg",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "EMPLOYMENT",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de vélos",
        description: "Vélos à louer pour le week-end.",
        city: "Nantes",
        price: 15,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Appareil photo reflex",
        description: "Appareil photo reflex en excellent état, avec objectif.",
        city: "Lille",
        price: 400,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche stage en informatique",
        description: "Étudiant en informatique cherche un stage.",
        city: "Marseille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "EMPLOYMENT",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Lit double à vendre",
        description: "Lit double en bois avec matelas.",
        city: "Toulouse",
        price: 200,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de livres",
        description: "Livres d'occasion à vendre, tous genres confondus.",
        city: "Bordeaux",
        price: 80,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Service de nettoyage",
        description: "Propose un service de nettoyage pour maisons et bureaux.",
        city: "Nice",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Téléviseur 4K",
        description: "Téléviseur 4K, excellent état.",
        city: "Paris",
        price: 500,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche baby-sitter",
        description: "Famille cherche une baby-sitter pour les soirées.",
        city: "Strasbourg",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de vêtements d'été",
        description: "Vêtements d'été à vendre, jamais portés.",
        city: "Marseille",
        price: 60,
        typeEnum: "OFFER",
        categoryEnum: "FASHION",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Salle de bain à rénover",
        description: "Recherche artisan pour rénovation de salle de bain.",
        city: "Lyon",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Canapé d'angle",
        description: "Canapé d'angle en cuir, très confortable.",
        city: "Bordeaux",
        price: 400,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cuisinière à gaz",
        description: "Cuisinière à gaz en excellent état.",
        city: "Nantes",
        price: 200,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche photographe",
        description: "Je cherche un photographe pour un événement.",
        city: "Nice",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Jeux vidéo à vendre",
        description: "Collection de jeux vidéo à vendre, tous supports.",
        city: "Marseille",
        price: 150,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de matériel de ski",
        description: "Matériel de ski à louer pour la saison.",
        city: "Chamonix",
        price: 50,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Réparation de vélos",
        description: "Je propose mes services de réparation de vélos.",
        city: "Lyon",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Lampe de bureau design",
        description: "Lampe de bureau design, presque neuve.",
        city: "Toulouse",
        price: 75,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche un coach sportif",
        description:
            "Je cherche un coach sportif pour des séances personnalisées.",
        city: "Paris",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends console de jeux",
        description: "Console de jeux en excellent état avec plusieurs jeux.",
        city: "Bordeaux",
        price: 250,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Guitare acoustique à vendre",
        description: "Guitare acoustique en bois, très peu utilisée.",
        city: "Marseille",
        price: 150,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Babysitting le week-end",
        description: "Je cherche des enfants à garder le week-end.",
        city: "Lyon",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Robe de soirée",
        description: "Robe de soirée jamais portée, taille M.",
        city: "Nice",
        price: 80,
        typeEnum: "OFFER",
        categoryEnum: "FASHION",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Appartements à louer",
        description: "Plusieurs appartements à louer en centre-ville.",
        city: "Strasbourg",
        price: 800,
        typeEnum: "OFFER",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Service de traduction",
        description:
            "Je propose des services de traduction pour vos documents.",
        city: "Toulouse",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Bouteille de vin vintage",
        description: "Bouteille de vin vintage, à collectionner.",
        city: "Bordeaux",
        price: 150,
        typeEnum: "OFFER",
        categoryEnum: "OTHERS",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de plantes d'intérieur",
        description: "Plantes d'intérieur à vendre, en très bonne santé.",
        city: "Marseille",
        price: 40,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche colocataire",
        description: "Je cherche un colocataire pour un appartement à Lyon.",
        city: "Lyon",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends bicyclettes anciennes",
        description:
            "Véhicules anciens en bon état, parfaits pour les collectionneurs.",
        city: "Toulouse",
        price: 350,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Réparation de smartphones",
        description: "Service de réparation de smartphones à domicile.",
        city: "Nantes",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Montre connectée",
        description:
            "Montre connectée en excellent état, toutes fonctionnalités.",
        city: "Strasbourg",
        price: 120,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de voiture",
        description: "Voiture à louer pour le week-end.",
        city: "Paris",
        price: 70,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Service de nettoyage de tapis",
        description: "Propose un service de nettoyage de tapis à domicile.",
        city: "Marseille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Collection de bandes dessinées",
        description: "Bandes dessinées anciennes, en très bon état.",
        city: "Lille",
        price: 90,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Propose cours de yoga",
        description:
            "Cours de yoga pour tous niveaux, en groupe ou individuel.",
        city: "Nice",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends kit de couture",
        description: "Kit de couture complet avec tous les accessoires.",
        city: "Bordeaux",
        price: 30,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche un entraîneur personnel",
        description:
            "Je cherche un entraîneur personnel pour un suivi personnalisé.",
        city: "Lyon",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Bureau à louer",
        description:
            "Bureau à louer dans un espace partagé, idéal pour freelances.",
        city: "Nantes",
        price: 200,
        typeEnum: "OFFER",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends équipement de camping",
        description: "Équipement de camping complet, presque neuf.",
        city: "Toulouse",
        price: 150,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends téléviseur ancien",
        description:
            "Téléviseur vintage en état de marche, idéal pour collection.",
        city: "Marseille",
        price: 80,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Service de jardinage",
        description: "Je propose mes services de jardinage pour particuliers.",
        city: "Lille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chaussures de randonnée",
        description: "Chaussures de randonnée presque neuves, taille 42.",
        city: "Nantes",
        price: 60,
        typeEnum: "OFFER",
        categoryEnum: "FASHION",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche un cours de peinture",
        description: "Je cherche un cours de peinture pour débutants.",
        city: "Paris",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de jeux d'échecs",
        description: "Jeux d'échecs en bois, idéal pour les passionnés.",
        city: "Bordeaux",
        price: 40,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Table de salon",
        description: "Table de salon en verre, en parfait état.",
        city: "Strasbourg",
        price: 150,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche d'un mentor",
        description: "Je cherche un mentor dans le domaine de la tech.",
        city: "Nice",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de vaisselle",
        description: "Vaisselle en porcelaine, très bon état.",
        city: "Toulouse",
        price: 70,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Réparation de bicyclettes",
        description: "Service de réparation de bicyclettes à domicile.",
        city: "Lille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends étagère en bois",
        description: "Étagère en bois massif, parfaite pour le rangement.",
        city: "Marseille",
        price: 120,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de guitare",
        description: "Je donne des cours de guitare pour débutants.",
        city: "Bordeaux",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends console de jeux vidéo",
        description: "Console de jeux vidéo avec plusieurs jeux inclus.",
        city: "Lyon",
        price: 300,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de salle pour événements",
        description: "Salle à louer pour événements, mariages, anniversaires.",
        city: "Toulouse",
        price: 1000,
        typeEnum: "OFFER",
        categoryEnum: "REAL_ESTATE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Propose cours de cuisine",
        description:
            "Cours de cuisine pour apprendre à préparer des plats simples.",
        city: "Nice",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Collection de vinyles",
        description: "Vinyles rares à vendre, en très bon état.",
        city: "Marseille",
        price: 200,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Réparation de meubles",
        description:
            "Service de réparation et restauration de meubles anciens.",
        city: "Bordeaux",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends smartphone",
        description: "Smartphone en excellent état, avec tous les accessoires.",
        city: "Lyon",
        price: 350,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Bureau de travail à vendre",
        description: "Bureau en bois massif, idéal pour le télétravail.",
        city: "Toulouse",
        price: 250,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Propose aide aux devoirs",
        description: "Aide aux devoirs pour enfants et adolescents.",
        city: "Nantes",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends vélo de course",
        description:
            "Vélo de course en très bon état, idéal pour les sportifs.",
        city: "Lille",
        price: 500,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de voiture électrique",
        description: "Voiture électrique à louer pour vos déplacements.",
        city: "Paris",
        price: 80,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends livres de cuisine",
        description: "Livres de cuisine en très bon état, pour tous niveaux.",
        city: "Nice",
        price: 50,
        typeEnum: "OFFER",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cherche un bon plan voyage",
        description:
            "Je cherche des conseils et bons plans pour voyager pas cher.",
        city: "Marseille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de fauteuils",
        description: "Fauteuils confortables, parfaits pour un salon.",
        city: "Toulouse",
        price: 200,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de danse",
        description: "Cours de danse moderne pour tous niveaux.",
        city: "Lille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends vélo électrique",
        description:
            "Vélo électrique en excellent état, parfait pour la ville.",
        city: "Bordeaux",
        price: 800,
        typeEnum: "OFFER",
        categoryEnum: "VEHICLE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cherche un partenaire de sport",
        description: "Je cherche quelqu'un pour pratiquer du sport ensemble.",
        city: "Marseille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends canapés",
        description: "Canapés en très bon état, à venir chercher.",
        city: "Nice",
        price: 400,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Service de babysitting",
        description: "Je propose des services de babysitting pour vos enfants.",
        city: "Lyon",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Recherche un cours de photographie",
        description: "Je cherche un cours de photographie pour débutants.",
        city: "Toulouse",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends une tablette",
        description: "Tablette en excellent état avec étui de protection.",
        city: "Strasbourg",
        price: 250,
        typeEnum: "OFFER",
        categoryEnum: "MULTIMEDIA",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de meubles de jardin",
        description: "Meubles de jardin en bois, très bon état.",
        city: "Bordeaux",
        price: 350,
        typeEnum: "OFFER",
        categoryEnum: "HOME",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de yoga",
        description: "Cours de yoga en extérieur, tous niveaux.",
        city: "Nantes",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "LEISURE",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Service de déménagement",
        description: "Propose mes services pour déménager.",
        city: "Lille",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vends vêtements de sport",
        description: "Vêtements de sport en très bon état, taille M.",
        city: "Marseille",
        price: 60,
        typeEnum: "OFFER",
        categoryEnum: "FASHION",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Réparation de bicyclettes",
        description: "Réparation de bicyclettes à domicile.",
        city: "Toulouse",
        price: 0,
        typeEnum: "DEMAND",
        categoryEnum: "SERVICES",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

export { ads };
