export const ads = [
    // ... (les 8 premières annonces comme précédemment)
    {
        title: "Location appartement 2 pièces",
        description:
            "Appartement 2 pièces à louer à Bordeaux, bien situé près du centre-ville.",
        address: "Bordeaux",
        price: 800,
        category: "immobilier",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente voiture électrique",
        description:
            "Voiture électrique en excellent état à vendre, faible kilométrage.",
        address: "Lyon",
        price: 25000,
        category: "véhicules",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Réparation de smartphone",
        description: "Service de réparation rapide de smartphones à domicile.",
        address: "Marseille",
        price: 50,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'un téléviseur 4K",
        description: "Téléviseur 4K à vendre, presque neuf, avec accessoires.",
        address: "Paris",
        price: 800,
        category: "électronique",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de matériel de jardinage",
        description:
            "Matériel de jardinage à louer pour particuliers et professionnels.",
        address: "Bordeaux",
        price: 100,
        category: "maison et jardin",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente vélo de montagne",
        description:
            "Vélo de montagne en très bon état, idéal pour les randonnées.",
        address: "Nice",
        price: 300,
        category: "loisirs",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chien à adopter",
        description: "Mignon petit chien à adopter, très joueur et affectueux.",
        address: "Toulouse",
        price: 0,
        category: "animaux",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente divers articles de décoration",
        description:
            "Articles de décoration pour la maison à vendre, style vintage.",
        address: "Lille",
        price: 150,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // Suite des annonces jusqu'à 200
    {
        title: "Location de scooter",
        description: "Scooter à louer pour explorer la ville.",
        address: "Nantes",
        price: 30,
        category: "véhicules",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'une tablette",
        description: "Tablette en excellent état, parfaite pour les étudiants.",
        address: "Rennes",
        price: 250,
        category: "électronique",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Nettoyage de tapis",
        description: "Service de nettoyage professionnel de tapis à domicile.",
        address: "Marseille",
        price: 60,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'un vélo de route",
        description: "Vélo de route haut de gamme, parfait pour les cyclistes.",
        address: "Bordeaux",
        price: 800,
        category: "véhicules",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location d'une salle de fête",
        description: "Salle de fête à louer pour événements privés.",
        address: "Lille",
        price: 500,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'outils de jardinage",
        description: "Outils de jardinage à vendre, en bon état.",
        address: "Strasbourg",
        price: 100,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Café à vendre",
        description:
            "Café à vendre dans le centre de Marseille, client fidèle.",
        address: "Marseille",
        price: 80000,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de kayak",
        description: "Kayak à louer pour des aventures aquatiques.",
        address: "Nice",
        price: 40,
        category: "loisirs",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de livres d'occasion",
        description: "Livres d'occasion en bon état, à vendre.",
        address: "Lyon",
        price: 5,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de costumes",
        description: "Costumes à louer pour événements ou fêtes.",
        address: "Toulouse",
        price: 60,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'un appareil photo",
        description: "Appareil photo reflex à vendre, avec objectifs.",
        address: "Paris",
        price: 500,
        category: "électronique",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chalet à louer",
        description: "Chalet à louer en montagne, idéal pour les vacances.",
        address: "Chamonix",
        price: 1200,
        category: "immobilier",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de meubles",
        description: "Meubles en bois massif à vendre, en très bon état.",
        address: "Lille",
        price: 300,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Garde d'enfants",
        description: "Service de garde d'enfants à domicile, expérimentée.",
        address: "Bordeaux",
        price: 15,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de vélo",
        description: "Vélo à louer pour explorer la ville.",
        address: "Nantes",
        price: 20,
        category: "véhicules",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de jouets",
        description: "Jouets d'occasion en bon état, à vendre.",
        address: "Strasbourg",
        price: 10,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chambre en colocation",
        description: "Chambre disponible en colocation à Toulouse.",
        address: "Toulouse",
        price: 400,
        category: "immobilier",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'une moto",
        description: "Moto à vendre, très peu utilisée, en excellent état.",
        address: "Marseille",
        price: 5000,
        category: "véhicules",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Services de jardinage",
        description: "Services de jardinage professionnels, tarif compétitif.",
        address: "Bordeaux",
        price: 30,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de vêtements",
        description: "Vêtements d'occasion en bon état, à vendre.",
        address: "Nice",
        price: 20,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chambre d'hôtes",
        description: "Chambre d'hôtes à louer dans une maison confortable.",
        address: "Marseille",
        price: 90,
        category: "immobilier",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'objets vintage",
        description: "Objets vintage à vendre, en très bon état.",
        address: "Paris",
        price: 75,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de danse",
        description: "Cours de danse pour tous niveaux.",
        address: "Lille",
        price: 15,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de vêtements pour enfants",
        description: "Vêtements pour enfants à vendre, état comme neuf.",
        address: "Toulouse",
        price: 50,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Échange de livres",
        description: "Échange de livres entre passionnés.",
        address: "Lyon",
        price: 0,
        category: "divers",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'un scooter",
        description: "Scooter en bon état, idéal pour la ville.",
        address: "Nice",
        price: 900,
        category: "véhicules",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Aide à la rédaction",
        description: "Aide à la rédaction de CV et lettres de motivation.",
        address: "Bordeaux",
        price: 30,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de matériel photo",
        description: "Appareil photo reflex à vendre, avec accessoires.",
        address: "Strasbourg",
        price: 500,
        category: "électronique",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de costumes",
        description: "Costumes à louer pour événements.",
        address: "Paris",
        price: 60,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de fournitures de bureau",
        description: "Fournitures de bureau à vendre, neuf et d'occasion.",
        address: "Lille",
        price: 50,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Soutien en informatique",
        description: "Aide en informatique pour tous niveaux.",
        address: "Toulouse",
        price: 20,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de matériels de jardinage",
        description: "Outils de jardinage à vendre, en bon état.",
        address: "Marseille",
        price: 75,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de matériel informatique",
        description: "Matériel informatique à louer pour événements.",
        address: "Lyon",
        price: 100,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de montres",
        description: "Montres de collection à vendre.",
        address: "Nice",
        price: 300,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Garde d'enfants",
        description: "Service de garde d'enfants à domicile.",
        address: "Bordeaux",
        price: 25,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de matériel de pêche",
        description: "Équipement de pêche à vendre, en excellent état.",
        address: "Strasbourg",
        price: 80,
        category: "loisirs",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Échange de vêtements",
        description: "Échange de vêtements entre amis.",
        address: "Paris",
        price: 0,
        category: "divers",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de services de nettoyage",
        description: "Service de nettoyage pour particuliers.",
        address: "Lille",
        price: 50,
        category: "services",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de vêtements de seconde main",
        description: "Vêtements de seconde main à vendre, en bon état.",
        address: "Toulouse",
        price: 30,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de cuisine",
        description: "Cours de cuisine à domicile, apprenez à cuisiner.",
        address: "Marseille",
        price: 40,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de table de jardin",
        description: "Table de jardin à vendre, en très bon état.",
        address: "Nice",
        price: 150,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Aide à la recherche d'emploi",
        description: "Aide à la recherche d'emploi, conseils et CV.",
        address: "Lyon",
        price: 30,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de jeux de société",
        description: "Jeux de société à vendre, en très bon état.",
        address: "Strasbourg",
        price: 25,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de bateaux",
        description: "Bateaux à louer pour vos sorties en mer.",
        address: "Bordeaux",
        price: 300,
        category: "loisirs",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de matériel de gym",
        description: "Matériel de gym à vendre, état neuf.",
        address: "Nice",
        price: 200,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chauffeur privé",
        description: "Service de chauffeur privé pour vos déplacements.",
        address: "Paris",
        price: 100,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de systèmes audio",
        description: "Systèmes audio à vendre, haute qualité.",
        address: "Lille",
        price: 300,
        category: "électronique",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de yoga",
        description: "Cours de yoga pour tous niveaux.",
        address: "Toulouse",
        price: 20,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'équipements de randonnée",
        description: "Équipements de randonnée à vendre, état impeccable.",
        address: "Marseille",
        price: 150,
        category: "loisirs",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Garde de chat",
        description: "Service de garde de chat à domicile.",
        address: "Bordeaux",
        price: 20,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de vélos",
        description: "Vélos en très bon état à vendre.",
        address: "Strasbourg",
        price: 250,
        category: "véhicules",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de guitare",
        description: "Cours de guitare à domicile, tous niveaux.",
        address: "Lyon",
        price: 30,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de jeux vidéo",
        description: "Jeux vidéo à vendre, toutes consoles.",
        address: "Paris",
        price: 40,
        category: "électronique",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chauffeur pour événements",
        description: "Service de chauffeur pour mariages et événements.",
        address: "Nice",
        price: 200,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de livres anciens",
        description: "Livres anciens à vendre, collection privée.",
        address: "Bordeaux",
        price: 60,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Aide aux devoirs",
        description: "Aide aux devoirs pour collégiens.",
        address: "Toulouse",
        price: 20,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de plantes d'intérieur",
        description: "Plantes d'intérieur à vendre, variétés variées.",
        address: "Marseille",
        price: 25,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de dessin",
        description: "Cours de dessin pour enfants et adultes.",
        address: "Lille",
        price: 35,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de matériel de camping",
        description: "Matériel de camping à vendre, en bon état.",
        address: "Strasbourg",
        price: 100,
        category: "loisirs",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Garde d'animaux",
        description: "Service de garde d'animaux à domicile.",
        address: "Paris",
        price: 25,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de skis",
        description: "Skis à vendre, en excellent état.",
        address: "Nice",
        price: 300,
        category: "sport",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de langues",
        description: "Cours de langues étrangères à domicile.",
        address: "Lyon",
        price: 25,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de bijoux faits main",
        description: "Bijoux faits main à vendre, uniques.",
        address: "Bordeaux",
        price: 40,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Échange de services",
        description: "Échange de services entre particuliers.",
        address: "Toulouse",
        price: 0,
        category: "divers",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de chaises",
        description: "Chaises à vendre, ensemble complet.",
        address: "Marseille",
        price: 150,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Atelier de poterie",
        description: "Atelier de poterie pour débutants.",
        address: "Lille",
        price: 40,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de planches de surf",
        description: "Planches de surf à vendre, état excellent.",
        address: "Nice",
        price: 350,
        category: "sport",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de matériel de photo",
        description: "Matériel de photo à vendre, état neuf.",
        address: "Strasbourg",
        price: 400,
        category: "électronique",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Garde de chien",
        description: "Service de garde de chien à domicile.",
        address: "Paris",
        price: 30,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de canapés",
        description: "Canapés à vendre, état impeccable.",
        address: "Bordeaux",
        price: 300,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location de voiture",
        description:
            "Voiture à louer, bien entretenue, disponible pour week-end.",
        address: "Marseille",
        price: 70,
        category: "véhicules",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de fournitures de bureau",
        description: "Fournitures de bureau à vendre en gros.",
        address: "Lyon",
        price: 200,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de cuisine",
        description: "Cours de cuisine à domicile, tous niveaux.",
        address: "Bordeaux",
        price: 50,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de meubles en bois",
        description: "Meubles en bois fait main à vendre.",
        address: "Toulouse",
        price: 600,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Balade à cheval",
        description: "Balades à cheval organisées pour petits et grands.",
        address: "Nice",
        price: 40,
        category: "loisirs",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Chambre à louer",
        description: "Chambre à louer dans un appartement à Paris.",
        address: "Paris",
        price: 600,
        category: "immobilier",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de plantes succulentes",
        description: "Plantes succulentes à vendre, variétés diverses.",
        address: "Strasbourg",
        price: 15,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Réparation de vélos",
        description: "Service de réparation de vélos à domicile.",
        address: "Lille",
        price: 30,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de montres",
        description: "Montres à vendre, état neuf.",
        address: "Toulouse",
        price: 150,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de yoga",
        description: "Cours de yoga pour tous niveaux.",
        address: "Marseille",
        price: 20,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'outils de jardinage",
        description: "Outils de jardinage à vendre, peu utilisés.",
        address: "Bordeaux",
        price: 100,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Échange de vêtements",
        description: "Échange de vêtements entre particuliers.",
        address: "Lyon",
        price: 0,
        category: "divers",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de chaises longues",
        description: "Chaises longues à vendre, parfaites pour l'été.",
        address: "Nice",
        price: 80,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Garde d'enfants",
        description: "Service de garde d'enfants à domicile.",
        address: "Toulouse",
        price: 15,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de matériel de sport",
        description: "Matériel de sport à vendre, état excellent.",
        address: "Strasbourg",
        price: 200,
        category: "loisirs",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente d'appareils photo",
        description: "Appareils photo à vendre, parfait pour les passionnés.",
        address: "Paris",
        price: 300,
        category: "électronique",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de danse",
        description: "Cours de danse pour tous niveaux, tous styles.",
        address: "Lille",
        price: 25,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de disques vinyles",
        description: "Disques vinyles à vendre, collection unique.",
        address: "Bordeaux",
        price: 50,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Réparation d'ordinateurs",
        description: "Service de réparation d'ordinateurs à domicile.",
        address: "Toulouse",
        price: 80,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Location d'un chalet",
        description: "Chalet à louer pour les vacances, proche des montagnes.",
        address: "Nice",
        price: 1500,
        category: "immobilier",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de matériel de musique",
        description: "Matériel de musique à vendre, état impeccable.",
        address: "Lille",
        price: 400,
        category: "électronique",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Cours de photographie",
        description: "Cours de photographie pour débutants.",
        address: "Strasbourg",
        price: 50,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de sacs à main",
        description: "Sacs à main à vendre, collection de marques.",
        address: "Paris",
        price: 100,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Garde de chats",
        description: "Service de garde de chats à domicile.",
        address: "Marseille",
        price: 25,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de vêtements d'été",
        description: "Vêtements d'été à vendre, collection récente.",
        address: "Toulouse",
        price: 50,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de matériel de bricolage",
        description: "Matériel de bricolage à vendre, à prix réduit.",
        address: "Bordeaux",
        price: 150,
        category: "maison et jardin",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Balade en bateau",
        description: "Balades en bateau sur la Seine.",
        address: "Paris",
        price: 80,
        category: "loisirs",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de produits bio",
        description: "Produits bio à vendre, en direct du producteur.",
        address: "Lille",
        price: 20,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Réparation de scooters",
        description: "Service de réparation de scooters à domicile.",
        address: "Marseille",
        price: 50,
        category: "services",
        type: "demande",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        title: "Vente de jouets",
        description: "Jouets à vendre, en bon état.",
        address: "Toulouse",
        price: 10,
        category: "divers",
        type: "offre",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];
